version: '3.5'

services:
    db:
        container_name: loja-db
        restart: always
        image: mysql:latest
        networks:
            network:
                ipv4_address: 172.11.0.3
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=loja_db

    app:
        container_name: loja-app
        restart: always
        image: ambientum/php:7.2-nginx
        networks:
            network:
                ipv4_address: 172.11.0.2
        volumes:
            - .:/var/www/app
        ports:
            - "8081:8080"
        links:
            - db

networks:
    network:
        name: loja-network
        driver: bridge
        ipam:
            config:
                - subnet: 172.11.0.0/16
